name: env
channels:
  - conda-forge
dependencies:
  # syncing to s3 buckets
  - s5cmd
  # ERA5 data
  - cdsapi>=0.7.4
  # routing
  - dask
  - distributed
  - geopandas
  - h5netcdf
  - matplotlib
  - natsort
  - netcdf4
  - networkx
  - numcodecs
  - pandas
  - pip
  - psutil
  - pyarrow
  - pyyaml
  - python
  - requests
  - s3fs
  - s5cmd
  - scipy
  - tqdm
  - xarray
  - zarr=2
  - pip:
      - river-route>=1.2.2
