name: update
channels:
  - conda-forge
  - defaults
dependencies:
  - aiobotocore
  - awscli
  - boto3
  - cdsapi>=0.7.4
  - dask
  - distributed
  - fastparquet
  - flox
  - h5netcdf
  - matplotlib
  - natsort
  - netcdf4
  - networkx
  - pandas
  - pip
  - psutil
  - pyyaml
  - python
  - requests
  - s3fs
  - s5cmd
  - scipy
  - tqdm
  - xarray
  - zarr=2