import os

# Parameters
MIN_LAG_TIME_DAYS = int(os.getenv('MIN_LAG_TIME_DAYS', 5))

DATA_DIR = os.getenv('WORK_DIR')
ERA5_DIR = os.getenv('ERA5_DIR')
CONFIGS_DIR = os.getenv('CONFIGS_DIR')
OUTPUTS_DIR = os.getenv('OUTPUTS_DIR')
HYDROSOS_DIR = os.getenv('HYDROSOS_DIR')

FINAL_STATES_DIR = os.getenv('FINAL_STATES_DIR')
S3_FINAL_STATES_DIR = os.getenv('S3_FINAL_STATES_DIR')

FORECAST_INITS_DIR = os.getenv('FORECAST_INITS_DIR')
S3_FORECAST_INITS_DIR = os.getenv('S3_FORECAST_INITS_DIR')

DAILY_ZARR = os.getenv('DAILY_ZARR')
HOURLY_ZARR = os.getenv('HOURLY_ZARR')
S3_DAILY_ZARR = os.getenv('S3_DAILY_ZARR')
S3_HOURLY_ZARR = os.getenv('S3_HOURLY_ZARR')

S3_CONFIGS_DIR = os.getenv('S3_CONFIGS_DIR')
S3_QFINAL_DIR = os.getenv('S3_QFINAL_DIR')
S3_MONTHLY_TIMESTEPS = os.getenv('S3_MONTHLY_TIMESTEPS')
S3_MONTHLY_TIMESERIES = os.getenv('S3_MONTHLY_TIMESERIES')
S3_ANNUAL_TIMESTEPS = os.getenv('S3_ANNUAL_TIMESTEPS')
S3_ANNUAL_TIMESERIES = os.getenv('S3_ANNUAL_TIMESERIES')
S3_ANNUAL_MAXIMUMS = os.getenv('S3_ANNUAL_MAXIMUMS')
